# Generated by Django 2.2.6 on 2019-10-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='periodicity',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
